[oauth.tokens.store.crypto]
  key = "XXX"
  iv = "XXX"

[redis]
  auth_pass = "XXX"
  host = "redis-redis.default.svc.cluster.local"
  port = 6379

[api]
  url = "https://api.friendsplus.me"

[http]
  url = "https://developers.friendsplus.me"

[log.logentries]
  enabled = false
  token = "XXX"

[session]
  secret = "XXX"
