# https://cloud.google.com/container-builder/docs/
#
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/node:$_VER', '.' ]
  id: 'build'

images:
- 'gcr.io/$PROJECT_ID/node:$_VER'
