---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: mongodb
provisioner: kubernetes.io/gce-pd
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Retain
parameters:
  # type: pd-standard
  type: pd-ssd
  fstype: ext4

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb
spec:
  storageClassName: mongodb
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi