---
kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    app: fpm-developers
  name: fpm-developers
data:
  PORT: "3000"

---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: fpm-developers
  name: fpm-developers
spec:
  type: NodePort
  sessionAffinity: None
  selector:
    app: fpm-developers
  ports:
    - name: service
      protocol: TCP
      targetPort: 3000
      port: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fpm-developers
  name: fpm-developers
spec:
  replicas: 1
  progressDeadlineSeconds: 600
  selector:
    matchLabels:
      app: fpm-developers
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fpm-developers
      name: fpm-developers
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      containers:
        - name: developers
          image: gcr.io/fpm-application/fpm-developers:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: fpm-developers
          ports:
            - containerPort: 3000
              name: service
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 8
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 1m
              memory: 100Mi
