---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fpm-landing-landing
  labels:
    app: landing
data:
  # landing
  PORT: "3000"
---
kind: Service
apiVersion: v1
metadata:
  name: fpm-landing-landing
  labels:
    app: fpm-landing-landing
spec:
  type: NodePort
  selector:
    app: landing
  ports:
    - name: service
      port: 6000
      targetPort: 3000
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fpm-landing-landing
  labels:
    app: landing
spec:
  replicas: 1
  progressDeadlineSeconds: 600
  selector:
    matchLabels:
      app: landing
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      name: fpm-landing-landing
      labels:
        app: landing
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      containers:
        - name: landing
          image: "gcr.io/fpm-application/fpm-landing-page:3.11.0"
          imagePullPolicy: "Always"
          ports:
            - name: service
              containerPort: 3000
          envFrom:
            - configMapRef:
                name: fpm-landing-landing
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 8
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 1m
              memory: 100Mi
