---
apiVersion: v1
kind: Secret
metadata:
  name: fpm-ipapi-fpm-ipapi
  labels:
    app: fpm-ipapi
type: Opaque
data:
  ipapi.clientToken: "XXX=="
  ipapi.imageProxyToken: "XXX=="
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fpm-ipapi-fpm-ipapi
  labels:
    app: fpm-ipapi
data:
  # Image Proxy API
  BUCKET_NAME: "fpm-user-assets"
  IMAGE_PROXY_URL: "https://image-proxy-dot-fpm-application.appspot.com"
  GOOGLE_APPLICATION_CREDENTIALS: "/secrets/ipapi/credentials.json"
---
kind: Service
apiVersion: v1
metadata:
  name: fpm-ipapi-fpm-ipapi
  labels:
    app: fpm-ipapi-fpm-ipapi
spec:
  type: NodePort
  selector:
    app: fpm-ipapi
  ports:
    - name: service
      port: 8080
      targetPort: 8080
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fpm-ipapi-fpm-ipapi
  labels:
    app: fpm-ipapi
spec:
  replicas: 1
  progressDeadlineSeconds: 600
  selector:
    matchLabels:
      app: fpm-ipapi
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      name: fpm-ipapi-fpm-ipapi
      labels:
        app: fpm-ipapi
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      containers:
        - name: ipapi
          image: "gcr.io/fpm-application/draft-web-image-proxy-api:latest"
          imagePullPolicy: "IfNotPresent"
          ports:
            - name: service
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: fpm-ipapi-fpm-ipapi
          env:
            - name: IMAGE_PROXY_TOKEN
              valueFrom:
                secretKeyRef:
                  name: fpm-ipapi-fpm-ipapi
                  key: ipapi.imageProxyToken
            - name: CLIENT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: fpm-ipapi-fpm-ipapi
                  key: ipapi.clientToken
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 8
            timeoutSeconds: 1
          volumeMounts:
            - name: ipapi-credentials
              mountPath: /secrets/ipapi
              readOnly: true
          resources:
            requests:
              cpu: 1m
              memory: 16Mi
      volumes:
        - name: ipapi-credentials
          secret:
            secretName: fpm-ipapi-credentials
