---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fpm-publisher
  name: fpm-publisher
spec:
  replicas: 1
  progressDeadlineSeconds: 600
  selector:
    matchLabels:
      app: fpm-publisher
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fpm-publisher
      name: fpm-publisher
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      containers:
        - name: publisher
          image: gcr.io/fpm-application/fpm-publisher:2.0.0
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: fpm-database
          ports:
            - containerPort: 8080
              name: service
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 8
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 1m
              memory: 150Mi
