---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fpm-crawler-crawler
  labels:
    app: crawler
data:
  # crawler
  PORT: "6000"
---
kind: Service
apiVersion: v1
metadata:
  name: fpm-crawler-crawler
  labels:
    app: fpm-crawler-crawler
spec:
  type: NodePort
  selector:
    app: crawler
  ports:
    - name: service
      port: 6000
      targetPort: 6000
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fpm-crawler-crawler
  labels:
    app: crawler
spec:
  replicas: 1
  progressDeadlineSeconds: 600
  selector:
    matchLabels:
      app: crawler
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      name: fpm-crawler-crawler
      labels:
        app: crawler
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      containers:
        - name: crawler
          image: "gcr.io/fpm-application/fpm-link-crawler:latest"
          imagePullPolicy: "Always"
          ports:
            - name: service
              containerPort: 6000
          envFrom:
            - configMapRef:
                name: fpm-crawler-crawler
          readinessProbe:
            httpGet:
              path: /health
              port: 6000
            initialDelaySeconds: 8
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 1m
              memory: 90Mi
