# https://cloud.google.com/container-builder/docs/
#
steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/fpm-link-crawler:latest",
        "-t",
        "gcr.io/$PROJECT_ID/fpm-link-crawler:$_VER",
        "-f",
        "services/fpm-web-link-crawler/Dockerfile",
        ".",
      ]
    id: "build"

images:
  - "gcr.io/$PROJECT_ID/fpm-link-crawler:latest"
  - "gcr.io/$PROJECT_ID/fpm-link-crawler:$_VER"
