runtime: go111
service: image-proxy

# https://cloud.google.com/appengine/docs/go/config/appref#automatic_scaling
instance_class: F1
automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: 1
  min_pending_latency: 300ms
  max_pending_latency: automatic
  max_concurrent_requests: 80

# handlers:
#   - url: /.*
#     script: _go_app

env_variables:
  BUCKET_NAME: 'fpm-user-assets'
  CLIENT_TOKEN: 'XXX'
